"""Seed data for the Maths Fundamentals add-on.

Strand 2: Number Bonds
This file is designed to sit beside early_number_sense_seed.py in the
fundamentals/ folder and be read directly by the app/Codex.
"""

STRANDS = [{'StrandID': 'NB',
  'StrandName': 'Number Bonds',
  'Description': 'Recall and apply number bonds using precise missing-number facts.'}]

LEVELS = [{'StrandID': 'NB',
  'Level': 1,
  'Skill': 'Bonds within 5',
  'ExpectedYear': 'R',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 1,
  'SuccessCriteria': 'Complete missing-number bonds where the total is no greater than 5.'},
 {'StrandID': 'NB',
  'Level': 2,
  'Skill': 'Bonds to 5',
  'ExpectedYear': 'R',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 1,
  'SuccessCriteria': 'Recall pairs of numbers that total 5.'},
 {'StrandID': 'NB',
  'Level': 3,
  'Skill': 'Bonds within 10',
  'ExpectedYear': 'Y1',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 1,
  'SuccessCriteria': 'Complete missing-number bonds where the total is no greater than 10.'},
 {'StrandID': 'NB',
  'Level': 4,
  'Skill': 'Bonds to 10',
  'ExpectedYear': 'Y1',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 1,
  'SuccessCriteria': 'Recall pairs of numbers that total 10.'},
 {'StrandID': 'NB',
  'Level': 5,
  'Skill': 'Bonds to 20',
  'ExpectedYear': 'Y1/Y2',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 1,
  'SuccessCriteria': 'Recall pairs of whole numbers that total 20.'},
 {'StrandID': 'NB',
  'Level': 6,
  'Skill': 'Bonds within 20 crossing 10',
  'ExpectedYear': 'Y2',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 5,
  'SuccessCriteria': 'Complete missing-number bonds to teen totals where the completed addition crosses 10.'},
 {'StrandID': 'NB',
  'Level': 7,
  'Skill': 'Bonds to 50',
  'ExpectedYear': 'Y2',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 5,
  'SuccessCriteria': 'Recall and derive pairs of whole numbers that total 50.'},
 {'StrandID': 'NB',
  'Level': 8,
  'Skill': 'Bonds to 100 in tens',
  'ExpectedYear': 'Y2/Y3',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 5,
  'SuccessCriteria': 'Recall complements to 100 using multiples of 10.'},
 {'StrandID': 'NB',
  'Level': 9,
  'Skill': 'Bonds to 100',
  'ExpectedYear': 'Y3',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 5,
  'SuccessCriteria': 'Find complements to 100 using non-multiples of 10.'},
 {'StrandID': 'NB',
  'Level': 10,
  'Skill': 'Bonds to 1000',
  'ExpectedYear': 'Y4',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 5,
  'SuccessCriteria': 'Find complements to 1000 using whole numbers.'},
 {'StrandID': 'NB',
  'Level': 11,
  'Skill': 'Decimal bonds to 1',
  'ExpectedYear': 'Y4/Y5',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 5,
  'SuccessCriteria': 'Find decimal complements to 1 using tenths and hundredths.'},
 {'StrandID': 'NB',
  'Level': 12,
  'Skill': 'Decimal bonds to 10',
  'ExpectedYear': 'Y5',
  'PassMark': 70,
  'QuestionsPerTest': 10,
  'KS2StartRecommended': 5,
  'SuccessCriteria': 'Find decimal complements to 10 using tenths and hundredths.'}]

QUESTIONS = [{'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-001',
  'QuestionType': 'missing_number',
  'Question': '2 + __ = 5',
  'Answer': '3',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 0 = 2',
  'Answer': '2',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-003',
  'QuestionType': 'missing_number',
  'Question': '4 = 2 + __',
  'Answer': '2',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-004',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 5',
  'Answer': '1',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-005',
  'QuestionType': 'missing_number',
  'Question': '__ + 4 = 4',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-006',
  'QuestionType': 'missing_number',
  'Question': '3 = 3 + __',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-007',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 4',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-008',
  'QuestionType': 'missing_number',
  'Question': '__ + 3 = 3',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-009',
  'QuestionType': 'missing_number',
  'Question': '5 = 1 + __',
  'Answer': '4',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-010',
  'QuestionType': 'missing_number',
  'Question': '2 + __ = 3',
  'Answer': '1',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-011',
  'QuestionType': 'missing_number',
  'Question': '__ + 2 = 5',
  'Answer': '3',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-012',
  'QuestionType': 'missing_number',
  'Question': '4 = 1 + __',
  'Answer': '3',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-013',
  'QuestionType': 'missing_number',
  'Question': '1 + __ = 2',
  'Answer': '1',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 2 = 2',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-015',
  'QuestionType': 'missing_number',
  'Question': '5 = 5 + __',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-016',
  'QuestionType': 'missing_number',
  'Question': '0 + __ = 5',
  'Answer': '5',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-017',
  'QuestionType': 'missing_number',
  'Question': '__ + 2 = 3',
  'Answer': '1',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-018',
  'QuestionType': 'missing_number',
  'Question': '4 = 3 + __',
  'Answer': '1',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-019',
  'QuestionType': 'missing_number',
  'Question': '2 + __ = 5',
  'Answer': '3',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-020',
  'QuestionType': 'missing_number',
  'Question': '__ + 0 = 2',
  'Answer': '2',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-021',
  'QuestionType': 'missing_number',
  'Question': '4 = 2 + __',
  'Answer': '2',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-022',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 5',
  'Answer': '1',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-023',
  'QuestionType': 'missing_number',
  'Question': '__ + 4 = 4',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-024',
  'QuestionType': 'missing_number',
  'Question': '3 = 3 + __',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-025',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 4',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 3 = 3',
  'Answer': '0',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-027',
  'QuestionType': 'missing_number',
  'Question': '5 = 1 + __',
  'Answer': '4',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-028',
  'QuestionType': 'missing_number',
  'Question': '2 + __ = 3',
  'Answer': '1',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-029',
  'QuestionType': 'missing_number',
  'Question': '__ + 2 = 5',
  'Answer': '3',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 1,
  'QuestionID': 'NB1-030',
  'QuestionType': 'missing_number',
  'Question': '4 = 1 + __',
  'Answer': '3',
  'StrictRule': 'Totals 2-5 only. No total above 5.',
  'SkillTag': 'bonds_within_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-001',
  'QuestionType': 'missing_number',
  'Question': '0 + __ = 5',
  'Answer': '5',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 4 = 5',
  'Answer': '1',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-003',
  'QuestionType': 'missing_number',
  'Question': '5 = 2 + __',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-004',
  'QuestionType': 'missing_number',
  'Question': '5 = __ + 2',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-005',
  'QuestionType': 'missing_number',
  'Question': '1 + __ = 5',
  'Answer': '4',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-006',
  'QuestionType': 'missing_number',
  'Question': '5 + __ = 5',
  'Answer': '0',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-007',
  'QuestionType': 'missing_number',
  'Question': '__ + 5 = 5',
  'Answer': '0',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-008',
  'QuestionType': 'missing_number',
  'Question': '5 = 1 + __',
  'Answer': '4',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-009',
  'QuestionType': 'missing_number',
  'Question': '5 = __ + 3',
  'Answer': '2',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-010',
  'QuestionType': 'missing_number',
  'Question': '2 + __ = 5',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-011',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 5',
  'Answer': '1',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-012',
  'QuestionType': 'missing_number',
  'Question': '__ + 0 = 5',
  'Answer': '5',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-013',
  'QuestionType': 'missing_number',
  'Question': '5 = 0 + __',
  'Answer': '5',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-014',
  'QuestionType': 'missing_number',
  'Question': '5 = __ + 4',
  'Answer': '1',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-015',
  'QuestionType': 'missing_number',
  'Question': '3 + __ = 5',
  'Answer': '2',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-016',
  'QuestionType': 'missing_number',
  'Question': '3 + __ = 5',
  'Answer': '2',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-017',
  'QuestionType': 'missing_number',
  'Question': '__ + 1 = 5',
  'Answer': '4',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-018',
  'QuestionType': 'missing_number',
  'Question': '5 = 5 + __',
  'Answer': '0',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-019',
  'QuestionType': 'missing_number',
  'Question': '5 = __ + 5',
  'Answer': '0',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-020',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 5',
  'Answer': '1',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-021',
  'QuestionType': 'missing_number',
  'Question': '2 + __ = 5',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 2 = 5',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-023',
  'QuestionType': 'missing_number',
  'Question': '5 = 4 + __',
  'Answer': '1',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-024',
  'QuestionType': 'missing_number',
  'Question': '5 = __ + 0',
  'Answer': '5',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-025',
  'QuestionType': 'missing_number',
  'Question': '5 + __ = 5',
  'Answer': '0',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-026',
  'QuestionType': 'missing_number',
  'Question': '1 + __ = 5',
  'Answer': '4',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-027',
  'QuestionType': 'missing_number',
  'Question': '__ + 3 = 5',
  'Answer': '2',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-028',
  'QuestionType': 'missing_number',
  'Question': '5 = 3 + __',
  'Answer': '2',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-029',
  'QuestionType': 'missing_number',
  'Question': '5 = __ + 1',
  'Answer': '4',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 2,
  'QuestionID': 'NB2-030',
  'QuestionType': 'missing_number',
  'Question': '0 + __ = 5',
  'Answer': '5',
  'StrictRule': 'Every question must total exactly 5.',
  'SkillTag': 'bonds_to_5'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-001',
  'QuestionType': 'missing_number',
  'Question': '3 + __ = 7',
  'Answer': '4',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 0 = 8',
  'Answer': '8',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-003',
  'QuestionType': 'missing_number',
  'Question': '7 = 5 + __',
  'Answer': '2',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-004',
  'QuestionType': 'missing_number',
  'Question': '9 = __ + 1',
  'Answer': '8',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-005',
  'QuestionType': 'missing_number',
  'Question': '9 + __ = 9',
  'Answer': '0',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 5 = 9',
  'Answer': '4',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-007',
  'QuestionType': 'missing_number',
  'Question': '8 = 7 + __',
  'Answer': '1',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-008',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 5',
  'Answer': '5',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-009',
  'QuestionType': 'missing_number',
  'Question': '0 + __ = 8',
  'Answer': '8',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 4 = 9',
  'Answer': '5',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-011',
  'QuestionType': 'missing_number',
  'Question': '6 = 0 + __',
  'Answer': '6',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-012',
  'QuestionType': 'missing_number',
  'Question': '9 = __ + 9',
  'Answer': '0',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-013',
  'QuestionType': 'missing_number',
  'Question': '1 + __ = 6',
  'Answer': '5',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 7 = 8',
  'Answer': '1',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-015',
  'QuestionType': 'missing_number',
  'Question': '9 = 7 + __',
  'Answer': '2',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-016',
  'QuestionType': 'missing_number',
  'Question': '8 = __ + 3',
  'Answer': '5',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-017',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 7',
  'Answer': '3',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 0 = 6',
  'Answer': '6',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-019',
  'QuestionType': 'missing_number',
  'Question': '8 = 4 + __',
  'Answer': '4',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-020',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 1',
  'Answer': '9',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-021',
  'QuestionType': 'missing_number',
  'Question': '2 + __ = 9',
  'Answer': '7',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 0 = 10',
  'Answer': '10',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-023',
  'QuestionType': 'missing_number',
  'Question': '8 = 6 + __',
  'Answer': '2',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-024',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 2',
  'Answer': '8',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-025',
  'QuestionType': 'missing_number',
  'Question': '6 + __ = 9',
  'Answer': '3',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 5 = 8',
  'Answer': '3',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-027',
  'QuestionType': 'missing_number',
  'Question': '10 = 0 + __',
  'Answer': '10',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-028',
  'QuestionType': 'missing_number',
  'Question': '8 = __ + 6',
  'Answer': '2',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-029',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 6',
  'Answer': '2',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 3,
  'QuestionID': 'NB3-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 1 = 7',
  'Answer': '6',
  'StrictRule': 'Totals 6-10 only. No total above 10.',
  'SkillTag': 'bonds_within_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-001',
  'QuestionType': 'missing_number',
  'Question': '0 + __ = 10',
  'Answer': '10',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 7 = 10',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-003',
  'QuestionType': 'missing_number',
  'Question': '10 = 6 + __',
  'Answer': '4',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-004',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 1',
  'Answer': '9',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-005',
  'QuestionType': 'missing_number',
  'Question': '1 + __ = 10',
  'Answer': '9',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 6 = 10',
  'Answer': '4',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-007',
  'QuestionType': 'missing_number',
  'Question': '10 = 7 + __',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-008',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 0',
  'Answer': '10',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-009',
  'QuestionType': 'missing_number',
  'Question': '2 + __ = 10',
  'Answer': '8',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 5 = 10',
  'Answer': '5',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-011',
  'QuestionType': 'missing_number',
  'Question': '10 = 8 + __',
  'Answer': '2',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-012',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 10',
  'Answer': '0',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-013',
  'QuestionType': 'missing_number',
  'Question': '3 + __ = 10',
  'Answer': '7',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 4 = 10',
  'Answer': '6',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-015',
  'QuestionType': 'missing_number',
  'Question': '10 = 9 + __',
  'Answer': '1',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-016',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 9',
  'Answer': '1',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-017',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 10',
  'Answer': '6',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 3 = 10',
  'Answer': '7',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-019',
  'QuestionType': 'missing_number',
  'Question': '10 = 10 + __',
  'Answer': '0',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-020',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 8',
  'Answer': '2',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-021',
  'QuestionType': 'missing_number',
  'Question': '5 + __ = 10',
  'Answer': '5',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 2 = 10',
  'Answer': '8',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-023',
  'QuestionType': 'missing_number',
  'Question': '10 = 0 + __',
  'Answer': '10',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-024',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 7',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-025',
  'QuestionType': 'missing_number',
  'Question': '6 + __ = 10',
  'Answer': '4',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 1 = 10',
  'Answer': '9',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-027',
  'QuestionType': 'missing_number',
  'Question': '10 = 1 + __',
  'Answer': '9',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-028',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 6',
  'Answer': '4',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-029',
  'QuestionType': 'missing_number',
  'Question': '7 + __ = 10',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 4,
  'QuestionID': 'NB4-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 0 = 10',
  'Answer': '10',
  'StrictRule': 'Every question must total exactly 10.',
  'SkillTag': 'bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-001',
  'QuestionType': 'missing_number',
  'Question': '1 + __ = 20',
  'Answer': '19',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 12 = 20',
  'Answer': '8',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-003',
  'QuestionType': 'missing_number',
  'Question': '20 = 15 + __',
  'Answer': '5',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-004',
  'QuestionType': 'missing_number',
  'Question': '20 = __ + 17',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-005',
  'QuestionType': 'missing_number',
  'Question': '10 + __ = 20',
  'Answer': '10',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 3 = 20',
  'Answer': '17',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-007',
  'QuestionType': 'missing_number',
  'Question': '20 = 5 + __',
  'Answer': '15',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-008',
  'QuestionType': 'missing_number',
  'Question': '20 = __ + 8',
  'Answer': '12',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-009',
  'QuestionType': 'missing_number',
  'Question': '19 + __ = 20',
  'Answer': '1',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 13 = 20',
  'Answer': '7',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-011',
  'QuestionType': 'missing_number',
  'Question': '20 = 14 + __',
  'Answer': '6',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-012',
  'QuestionType': 'missing_number',
  'Question': '20 = __ + 18',
  'Answer': '2',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-013',
  'QuestionType': 'missing_number',
  'Question': '9 + __ = 20',
  'Answer': '11',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 4 = 20',
  'Answer': '16',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-015',
  'QuestionType': 'missing_number',
  'Question': '20 = 4 + __',
  'Answer': '16',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-016',
  'QuestionType': 'missing_number',
  'Question': '20 = __ + 9',
  'Answer': '11',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-017',
  'QuestionType': 'missing_number',
  'Question': '18 + __ = 20',
  'Answer': '2',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 14 = 20',
  'Answer': '6',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-019',
  'QuestionType': 'missing_number',
  'Question': '20 = 13 + __',
  'Answer': '7',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-020',
  'QuestionType': 'missing_number',
  'Question': '20 = __ + 19',
  'Answer': '1',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-021',
  'QuestionType': 'missing_number',
  'Question': '8 + __ = 20',
  'Answer': '12',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 5 = 20',
  'Answer': '15',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-023',
  'QuestionType': 'missing_number',
  'Question': '20 = 3 + __',
  'Answer': '17',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-024',
  'QuestionType': 'missing_number',
  'Question': '20 = __ + 10',
  'Answer': '10',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-025',
  'QuestionType': 'missing_number',
  'Question': '17 + __ = 20',
  'Answer': '3',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 15 = 20',
  'Answer': '5',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-027',
  'QuestionType': 'missing_number',
  'Question': '20 = 12 + __',
  'Answer': '8',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-028',
  'QuestionType': 'missing_number',
  'Question': '20 = __ + 1',
  'Answer': '19',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-029',
  'QuestionType': 'missing_number',
  'Question': '7 + __ = 20',
  'Answer': '13',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 5,
  'QuestionID': 'NB5-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 6 = 20',
  'Answer': '14',
  'StrictRule': 'Every question must total exactly 20. Whole numbers only.',
  'SkillTag': 'bonds_to_20'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-001',
  'QuestionType': 'missing_number',
  'Question': '9 + __ = 16',
  'Answer': '7',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 8 = 14',
  'Answer': '6',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-003',
  'QuestionType': 'missing_number',
  'Question': '11 = 6 + __',
  'Answer': '5',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-004',
  'QuestionType': 'missing_number',
  'Question': '14 = __ + 9',
  'Answer': '5',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-005',
  'QuestionType': 'missing_number',
  'Question': '7 + __ = 12',
  'Answer': '5',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 7 = 13',
  'Answer': '6',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-007',
  'QuestionType': 'missing_number',
  'Question': '14 = 8 + __',
  'Answer': '6',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-008',
  'QuestionType': 'missing_number',
  'Question': '15 = __ + 6',
  'Answer': '9',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-009',
  'QuestionType': 'missing_number',
  'Question': '3 + __ = 12',
  'Answer': '9',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 8 = 11',
  'Answer': '3',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-011',
  'QuestionType': 'missing_number',
  'Question': '15 = 6 + __',
  'Answer': '9',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-012',
  'QuestionType': 'missing_number',
  'Question': '11 = __ + 9',
  'Answer': '2',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-013',
  'QuestionType': 'missing_number',
  'Question': '8 + __ = 11',
  'Answer': '3',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 2 = 11',
  'Answer': '9',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-015',
  'QuestionType': 'missing_number',
  'Question': '13 = 9 + __',
  'Answer': '4',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-016',
  'QuestionType': 'missing_number',
  'Question': '14 = __ + 5',
  'Answer': '9',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-017',
  'QuestionType': 'missing_number',
  'Question': '7 + __ = 11',
  'Answer': '4',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 4 = 12',
  'Answer': '8',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-019',
  'QuestionType': 'missing_number',
  'Question': '15 = 7 + __',
  'Answer': '8',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-020',
  'QuestionType': 'missing_number',
  'Question': '11 = __ + 6',
  'Answer': '5',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-021',
  'QuestionType': 'missing_number',
  'Question': '7 + __ = 16',
  'Answer': '9',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 8 = 17',
  'Answer': '9',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-023',
  'QuestionType': 'missing_number',
  'Question': '15 = 8 + __',
  'Answer': '7',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-024',
  'QuestionType': 'missing_number',
  'Question': '12 = __ + 3',
  'Answer': '9',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-025',
  'QuestionType': 'missing_number',
  'Question': '9 + __ = 18',
  'Answer': '9',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 7 = 12',
  'Answer': '5',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-027',
  'QuestionType': 'missing_number',
  'Question': '16 = 8 + __',
  'Answer': '8',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-028',
  'QuestionType': 'missing_number',
  'Question': '13 = __ + 8',
  'Answer': '5',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-029',
  'QuestionType': 'missing_number',
  'Question': '4 + __ = 12',
  'Answer': '8',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 6,
  'QuestionID': 'NB6-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 6 = 13',
  'Answer': '7',
  'StrictRule': 'Teen totals 11-19. Both parts below 10 and the completed addition must cross 10.',
  'SkillTag': 'bonds_within_20_crossing_10'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-001',
  'QuestionType': 'missing_number',
  'Question': '1 + __ = 50',
  'Answer': '49',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 48 = 50',
  'Answer': '2',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-003',
  'QuestionType': 'missing_number',
  'Question': '50 = 3 + __',
  'Answer': '47',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-004',
  'QuestionType': 'missing_number',
  'Question': '50 = __ + 46',
  'Answer': '4',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-005',
  'QuestionType': 'missing_number',
  'Question': '5 + __ = 50',
  'Answer': '45',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 44 = 50',
  'Answer': '6',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-007',
  'QuestionType': 'missing_number',
  'Question': '50 = 7 + __',
  'Answer': '43',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-008',
  'QuestionType': 'missing_number',
  'Question': '50 = __ + 42',
  'Answer': '8',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-009',
  'QuestionType': 'missing_number',
  'Question': '9 + __ = 50',
  'Answer': '41',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 40 = 50',
  'Answer': '10',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-011',
  'QuestionType': 'missing_number',
  'Question': '50 = 12 + __',
  'Answer': '38',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-012',
  'QuestionType': 'missing_number',
  'Question': '50 = __ + 35',
  'Answer': '15',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-013',
  'QuestionType': 'missing_number',
  'Question': '18 + __ = 50',
  'Answer': '32',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 30 = 50',
  'Answer': '20',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-015',
  'QuestionType': 'missing_number',
  'Question': '50 = 22 + __',
  'Answer': '28',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-016',
  'QuestionType': 'missing_number',
  'Question': '50 = __ + 25',
  'Answer': '25',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-017',
  'QuestionType': 'missing_number',
  'Question': '28 + __ = 50',
  'Answer': '22',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 20 = 50',
  'Answer': '30',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-019',
  'QuestionType': 'missing_number',
  'Question': '50 = 32 + __',
  'Answer': '18',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-020',
  'QuestionType': 'missing_number',
  'Question': '50 = __ + 15',
  'Answer': '35',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-021',
  'QuestionType': 'missing_number',
  'Question': '38 + __ = 50',
  'Answer': '12',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 10 = 50',
  'Answer': '40',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-023',
  'QuestionType': 'missing_number',
  'Question': '50 = 41 + __',
  'Answer': '9',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-024',
  'QuestionType': 'missing_number',
  'Question': '50 = __ + 8',
  'Answer': '42',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-025',
  'QuestionType': 'missing_number',
  'Question': '43 + __ = 50',
  'Answer': '7',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 6 = 50',
  'Answer': '44',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-027',
  'QuestionType': 'missing_number',
  'Question': '50 = 45 + __',
  'Answer': '5',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-028',
  'QuestionType': 'missing_number',
  'Question': '50 = __ + 4',
  'Answer': '46',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-029',
  'QuestionType': 'missing_number',
  'Question': '47 + __ = 50',
  'Answer': '3',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 7,
  'QuestionID': 'NB7-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 2 = 50',
  'Answer': '48',
  'StrictRule': 'Every question totals exactly 50. Whole numbers only.',
  'SkillTag': 'bonds_to_50'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-001',
  'QuestionType': 'missing_number',
  'Question': '0 + __ = 100',
  'Answer': '100',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 90 = 100',
  'Answer': '10',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-003',
  'QuestionType': 'missing_number',
  'Question': '100 = 20 + __',
  'Answer': '80',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-004',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 70',
  'Answer': '30',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-005',
  'QuestionType': 'missing_number',
  'Question': '40 + __ = 100',
  'Answer': '60',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 50 = 100',
  'Answer': '50',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-007',
  'QuestionType': 'missing_number',
  'Question': '100 = 60 + __',
  'Answer': '40',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-008',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 30',
  'Answer': '70',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-009',
  'QuestionType': 'missing_number',
  'Question': '80 + __ = 100',
  'Answer': '20',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 10 = 100',
  'Answer': '90',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-011',
  'QuestionType': 'missing_number',
  'Question': '100 = 0 + __',
  'Answer': '100',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-012',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 90',
  'Answer': '10',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-013',
  'QuestionType': 'missing_number',
  'Question': '20 + __ = 100',
  'Answer': '80',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 70 = 100',
  'Answer': '30',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-015',
  'QuestionType': 'missing_number',
  'Question': '100 = 40 + __',
  'Answer': '60',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-016',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 50',
  'Answer': '50',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-017',
  'QuestionType': 'missing_number',
  'Question': '60 + __ = 100',
  'Answer': '40',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 30 = 100',
  'Answer': '70',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-019',
  'QuestionType': 'missing_number',
  'Question': '100 = 80 + __',
  'Answer': '20',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-020',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 10',
  'Answer': '90',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-021',
  'QuestionType': 'missing_number',
  'Question': '0 + __ = 100',
  'Answer': '100',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 90 = 100',
  'Answer': '10',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-023',
  'QuestionType': 'missing_number',
  'Question': '100 = 20 + __',
  'Answer': '80',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-024',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 70',
  'Answer': '30',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-025',
  'QuestionType': 'missing_number',
  'Question': '40 + __ = 100',
  'Answer': '60',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 50 = 100',
  'Answer': '50',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-027',
  'QuestionType': 'missing_number',
  'Question': '100 = 60 + __',
  'Answer': '40',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-028',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 30',
  'Answer': '70',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-029',
  'QuestionType': 'missing_number',
  'Question': '80 + __ = 100',
  'Answer': '20',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 8,
  'QuestionID': 'NB8-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 10 = 100',
  'Answer': '90',
  'StrictRule': 'Every question totals 100. Given values and answers must be multiples of 10.',
  'SkillTag': 'bonds_to_100_tens'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-001',
  'QuestionType': 'missing_number',
  'Question': '3 + __ = 100',
  'Answer': '97',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 93 = 100',
  'Answer': '7',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-003',
  'QuestionType': 'missing_number',
  'Question': '100 = 12 + __',
  'Answer': '88',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-004',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 86',
  'Answer': '14',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-005',
  'QuestionType': 'missing_number',
  'Question': '18 + __ = 100',
  'Answer': '82',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 79 = 100',
  'Answer': '21',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-007',
  'QuestionType': 'missing_number',
  'Question': '100 = 24 + __',
  'Answer': '76',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-008',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 73',
  'Answer': '27',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-009',
  'QuestionType': 'missing_number',
  'Question': '31 + __ = 100',
  'Answer': '69',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 67 = 100',
  'Answer': '33',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-011',
  'QuestionType': 'missing_number',
  'Question': '100 = 36 + __',
  'Answer': '64',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-012',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 61',
  'Answer': '39',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-013',
  'QuestionType': 'missing_number',
  'Question': '42 + __ = 100',
  'Answer': '58',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 56 = 100',
  'Answer': '44',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-015',
  'QuestionType': 'missing_number',
  'Question': '100 = 47 + __',
  'Answer': '53',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-016',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 47',
  'Answer': '53',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-017',
  'QuestionType': 'missing_number',
  'Question': '56 + __ = 100',
  'Answer': '44',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 42 = 100',
  'Answer': '58',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-019',
  'QuestionType': 'missing_number',
  'Question': '100 = 61 + __',
  'Answer': '39',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-020',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 36',
  'Answer': '64',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-021',
  'QuestionType': 'missing_number',
  'Question': '67 + __ = 100',
  'Answer': '33',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 31 = 100',
  'Answer': '69',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-023',
  'QuestionType': 'missing_number',
  'Question': '100 = 73 + __',
  'Answer': '27',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-024',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 24',
  'Answer': '76',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-025',
  'QuestionType': 'missing_number',
  'Question': '79 + __ = 100',
  'Answer': '21',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 18 = 100',
  'Answer': '82',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-027',
  'QuestionType': 'missing_number',
  'Question': '100 = 86 + __',
  'Answer': '14',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-028',
  'QuestionType': 'missing_number',
  'Question': '100 = __ + 12',
  'Answer': '88',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-029',
  'QuestionType': 'missing_number',
  'Question': '93 + __ = 100',
  'Answer': '7',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 9,
  'QuestionID': 'NB9-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 3 = 100',
  'Answer': '97',
  'StrictRule': 'Every question totals 100. Use non-multiples of 10.',
  'SkillTag': 'bonds_to_100'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-001',
  'QuestionType': 'missing_number',
  'Question': '5 + __ = 1000',
  'Answer': '995',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 990 = 1000',
  'Answer': '10',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-003',
  'QuestionType': 'missing_number',
  'Question': '1000 = 25 + __',
  'Answer': '975',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-004',
  'QuestionType': 'missing_number',
  'Question': '1000 = __ + 950',
  'Answer': '50',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-005',
  'QuestionType': 'missing_number',
  'Question': '75 + __ = 1000',
  'Answer': '925',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 900 = 1000',
  'Answer': '100',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-007',
  'QuestionType': 'missing_number',
  'Question': '1000 = 125 + __',
  'Answer': '875',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-008',
  'QuestionType': 'missing_number',
  'Question': '1000 = __ + 850',
  'Answer': '150',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-009',
  'QuestionType': 'missing_number',
  'Question': '175 + __ = 1000',
  'Answer': '825',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 800 = 1000',
  'Answer': '200',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-011',
  'QuestionType': 'missing_number',
  'Question': '1000 = 225 + __',
  'Answer': '775',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-012',
  'QuestionType': 'missing_number',
  'Question': '1000 = __ + 750',
  'Answer': '250',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-013',
  'QuestionType': 'missing_number',
  'Question': '275 + __ = 1000',
  'Answer': '725',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 700 = 1000',
  'Answer': '300',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-015',
  'QuestionType': 'missing_number',
  'Question': '1000 = 325 + __',
  'Answer': '675',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-016',
  'QuestionType': 'missing_number',
  'Question': '1000 = __ + 650',
  'Answer': '350',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-017',
  'QuestionType': 'missing_number',
  'Question': '375 + __ = 1000',
  'Answer': '625',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 600 = 1000',
  'Answer': '400',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-019',
  'QuestionType': 'missing_number',
  'Question': '1000 = 425 + __',
  'Answer': '575',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-020',
  'QuestionType': 'missing_number',
  'Question': '1000 = __ + 550',
  'Answer': '450',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-021',
  'QuestionType': 'missing_number',
  'Question': '525 + __ = 1000',
  'Answer': '475',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 425 = 1000',
  'Answer': '575',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-023',
  'QuestionType': 'missing_number',
  'Question': '1000 = 625 + __',
  'Answer': '375',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-024',
  'QuestionType': 'missing_number',
  'Question': '1000 = __ + 325',
  'Answer': '675',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-025',
  'QuestionType': 'missing_number',
  'Question': '725 + __ = 1000',
  'Answer': '275',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 225 = 1000',
  'Answer': '775',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-027',
  'QuestionType': 'missing_number',
  'Question': '1000 = 825 + __',
  'Answer': '175',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-028',
  'QuestionType': 'missing_number',
  'Question': '1000 = __ + 125',
  'Answer': '875',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-029',
  'QuestionType': 'missing_number',
  'Question': '925 + __ = 1000',
  'Answer': '75',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 10,
  'QuestionID': 'NB10-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 25 = 1000',
  'Answer': '975',
  'StrictRule': 'Every question totals exactly 1000. Whole numbers only.',
  'SkillTag': 'bonds_to_1000'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-001',
  'QuestionType': 'missing_number',
  'Question': '0.1 + __ = 1',
  'Answer': '0.9',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.8 = 1',
  'Answer': '0.2',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-003',
  'QuestionType': 'missing_number',
  'Question': '1 = 0.3 + __',
  'Answer': '0.7',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-004',
  'QuestionType': 'missing_number',
  'Question': '1 = __ + 0.6',
  'Answer': '0.4',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-005',
  'QuestionType': 'missing_number',
  'Question': '0.5 + __ = 1',
  'Answer': '0.5',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.4 = 1',
  'Answer': '0.6',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-007',
  'QuestionType': 'missing_number',
  'Question': '1 = 0.7 + __',
  'Answer': '0.3',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-008',
  'QuestionType': 'missing_number',
  'Question': '1 = __ + 0.2',
  'Answer': '0.8',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-009',
  'QuestionType': 'missing_number',
  'Question': '0.9 + __ = 1',
  'Answer': '0.1',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.95 = 1',
  'Answer': '0.05',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-011',
  'QuestionType': 'missing_number',
  'Question': '1 = 0.15 + __',
  'Answer': '0.85',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-012',
  'QuestionType': 'missing_number',
  'Question': '1 = __ + 0.75',
  'Answer': '0.25',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-013',
  'QuestionType': 'missing_number',
  'Question': '0.35 + __ = 1',
  'Answer': '0.65',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.55 = 1',
  'Answer': '0.45',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-015',
  'QuestionType': 'missing_number',
  'Question': '1 = 0.55 + __',
  'Answer': '0.45',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-016',
  'QuestionType': 'missing_number',
  'Question': '1 = __ + 0.35',
  'Answer': '0.65',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-017',
  'QuestionType': 'missing_number',
  'Question': '0.75 + __ = 1',
  'Answer': '0.25',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.15 = 1',
  'Answer': '0.85',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-019',
  'QuestionType': 'missing_number',
  'Question': '1 = 0.95 + __',
  'Answer': '0.05',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-020',
  'QuestionType': 'missing_number',
  'Question': '1 = __ + 0.88',
  'Answer': '0.12',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-021',
  'QuestionType': 'missing_number',
  'Question': '0.18 + __ = 1',
  'Answer': '0.82',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.78 = 1',
  'Answer': '0.22',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-023',
  'QuestionType': 'missing_number',
  'Question': '1 = 0.28 + __',
  'Answer': '0.72',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-024',
  'QuestionType': 'missing_number',
  'Question': '1 = __ + 0.68',
  'Answer': '0.32',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-025',
  'QuestionType': 'missing_number',
  'Question': '0.38 + __ = 1',
  'Answer': '0.62',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.58 = 1',
  'Answer': '0.42',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-027',
  'QuestionType': 'missing_number',
  'Question': '1 = 0.48 + __',
  'Answer': '0.52',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-028',
  'QuestionType': 'missing_number',
  'Question': '1 = __ + 0.48',
  'Answer': '0.52',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-029',
  'QuestionType': 'missing_number',
  'Question': '0.68 + __ = 1',
  'Answer': '0.32',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 11,
  'QuestionID': 'NB11-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.18 = 1',
  'Answer': '0.82',
  'StrictRule': 'Every question totals exactly 1. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_1'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-001',
  'QuestionType': 'missing_number',
  'Question': '0.5 + __ = 10',
  'Answer': '9.5',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-002',
  'QuestionType': 'missing_number',
  'Question': '__ + 8.8 = 10',
  'Answer': '1.2',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-003',
  'QuestionType': 'missing_number',
  'Question': '10 = 1.5 + __',
  'Answer': '8.5',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-004',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 7.7',
  'Answer': '2.3',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-005',
  'QuestionType': 'missing_number',
  'Question': '2.5 + __ = 10',
  'Answer': '7.5',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-006',
  'QuestionType': 'missing_number',
  'Question': '__ + 6.9 = 10',
  'Answer': '3.1',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-007',
  'QuestionType': 'missing_number',
  'Question': '10 = 3.4 + __',
  'Answer': '6.6',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-008',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 6.25',
  'Answer': '3.75',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-009',
  'QuestionType': 'missing_number',
  'Question': '4.2 + __ = 10',
  'Answer': '5.8',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-010',
  'QuestionType': 'missing_number',
  'Question': '__ + 5.5 = 10',
  'Answer': '4.5',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-011',
  'QuestionType': 'missing_number',
  'Question': '10 = 4.8 + __',
  'Answer': '5.2',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-012',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 4.9',
  'Answer': '5.1',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-013',
  'QuestionType': 'missing_number',
  'Question': '5.25 + __ = 10',
  'Answer': '4.75',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-014',
  'QuestionType': 'missing_number',
  'Question': '__ + 4.5 = 10',
  'Answer': '5.5',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-015',
  'QuestionType': 'missing_number',
  'Question': '10 = 5.8 + __',
  'Answer': '4.2',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-016',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 3.8',
  'Answer': '6.2',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-017',
  'QuestionType': 'missing_number',
  'Question': '6.4 + __ = 10',
  'Answer': '3.6',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-018',
  'QuestionType': 'missing_number',
  'Question': '__ + 3.25 = 10',
  'Answer': '6.75',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-019',
  'QuestionType': 'missing_number',
  'Question': '10 = 7.1 + __',
  'Answer': '2.9',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-020',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 2.5',
  'Answer': '7.5',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-021',
  'QuestionType': 'missing_number',
  'Question': '7.8 + __ = 10',
  'Answer': '2.2',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-022',
  'QuestionType': 'missing_number',
  'Question': '__ + 1.8 = 10',
  'Answer': '8.2',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-023',
  'QuestionType': 'missing_number',
  'Question': '10 = 8.4 + __',
  'Answer': '1.6',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-024',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 1.25',
  'Answer': '8.75',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-025',
  'QuestionType': 'missing_number',
  'Question': '9.1 + __ = 10',
  'Answer': '0.9',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-026',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.8 = 10',
  'Answer': '9.2',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-027',
  'QuestionType': 'missing_number',
  'Question': '10 = 9.4 + __',
  'Answer': '0.6',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-028',
  'QuestionType': 'missing_number',
  'Question': '10 = __ + 0.5',
  'Answer': '9.5',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-029',
  'QuestionType': 'missing_number',
  'Question': '9.75 + __ = 10',
  'Answer': '0.25',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'},
 {'StrandID': 'NB',
  'Level': 12,
  'QuestionID': 'NB12-030',
  'QuestionType': 'missing_number',
  'Question': '__ + 0.2 = 10',
  'Answer': '9.8',
  'StrictRule': 'Every question totals exactly 10. Use decimals to 1 or 2 decimal places.',
  'SkillTag': 'decimal_bonds_to_10'}]
